import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = path.join(rootDir, 'prisma', 'schema.prisma');
const testSchemaPath = path.join(rootDir, 'prisma', 'schema.test.prisma');
const dbPath = path.join(rootDir, 'prisma', 'test.db');
const generatedClientPath = path.join(rootDir, 'src', 'generated', 'prisma-test');

const SYNC_MARKER = '// ---- SYNC-MARKER:';

const TEST_SCHEMA_HEADER = `// AUTO-GENERATED by prisma/setup-test-db.ts from schema.prisma. Do not edit
// by hand — edit the models in schema.prisma instead and rerun the tests.

generator client {
  provider               = "prisma-client"
  output                 = "../src/generated/prisma-test"
  runtime                = "nodejs"
  moduleFormat           = "esm"
  generatedFileExtension = "ts"
  importFileExtension    = "js"
}

datasource db {
  provider = "sqlite"
}

`;

function syncTestSchema(): void {
  const source = readFileSync(schemaPath, 'utf8');
  const markerIndex = source.indexOf(SYNC_MARKER);
  if (markerIndex === -1) {
    throw new Error(`Could not find sync marker in schema.prisma:\n${SYNC_MARKER}`);
  }

  const sharedModels = source.slice(markerIndex);
  writeFileSync(testSchemaPath, TEST_SCHEMA_HEADER + sharedModels);
}

function run(args: string[]): void {
  // `shell: true` is required for npx resolution on Windows (npx.cmd). Safe
  // here: the command and args are fixed literals, never user input.
  execFileSync('npx', args, { stdio: 'inherit', cwd: rootDir, shell: true });
}

function main(): void {
  syncTestSchema();

  if (existsSync(dbPath)) {
    unlinkSync(dbPath);
  }
  // A prior interrupted run can leave a partial output directory that
  // `prisma generate` then refuses to write into ("exists and is not empty
  // but doesn't look like a generated Prisma Client") — always start clean.
  if (existsSync(generatedClientPath)) {
    rmSync(generatedClientPath, { recursive: true, force: true });
  }

  const dbUrl = `file:${dbPath}`;
  // No --accept-data-loss: the file was just deleted above, so this is
  // always a push to an empty database — there is nothing to warn about.
  run(['prisma', 'db', 'push', '--schema', testSchemaPath, '--url', dbUrl]);
  run(['prisma', 'generate', '--schema', testSchemaPath]);
}

main();
